# Generated by Django 3.1.3 on 2020-11-22 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel',
            new_name='Hotel_Info',
        ),
    ]
