# Generated by Django 3.1.3 on 2020-11-22 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20201122_1000'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel_Info',
            new_name='HotelInfo',
        ),
    ]
